version: '3'
services:
  zalenium:
    image: dosel/zalenium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    privileged: true
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 7
            --maxDockerSeleniumContainers 14
            --screenWidth 1366 --screenHeight 768
            --timeZone America/Denver
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --sendAnonymousUsageInfo false
            --maxTestSessions 1000
    environment:
      - PULL_SELENIUM_IMAGE=true
      - WAIT_FOR_AVAILABLE_NODES=false
      - CHECK_CONTAINERS_INTERVAL=20000
      - "zalenium_no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1"


# In order to run the images we need to type in the terminal 

# sudo nano /etc/hosts

# (it opens the file --> hosts)

# - add the next line

# 127.0.0.1 zalenium

# then Control+X to exit and we say yes to save changes.

# We are all set! GAB
